### ISSUE TITLE
Error on initial load

### ISSUE THREAD

**Issue by danielwaltz** [kilkelly/redux-localstorage-simple#11]
I've noticed when viewing my app from a fresh browser than the initial load triggers an error despite everything working correctly.

`[Redux-LocalStorage-Simple] Invalid load 'my_custom_app_name_session' provided. Check your 'states' in 'load()'`

I'm sharing the same config to my `save()` and `load()` functions:

```js
const localStorageConfig = {
  states: ['session'],
  namespace: 'my_custom_app_name',
};

save(localStorageConfig);

load(localStorageConfig);
```

Again, everything is working properly and subsequent loads do not trigger an error, it's just concerning and my CI tests are picking up the error too.

**Comment by kilkelly** [comment]
I am using `console.error` to.display this message. However I am now thinking to use `console.warn` or `console.info` as it's ambiguous whether this situation warrants an error message. Would either of these alternatives trigger your CI tests? I should also rephrase this message to better explain why this situation happens.

**Comment by danielwaltz** [comment]
@kilkelly All types of logs are being displayed in my CI testing (my prod should not include any). I could make adjustments to suppress `console.info` and/or `console.log` though, but I guess I don't have an understanding why this instance is being logged at all. Perhaps just a comment in the source would be sufficient seeing as everything works fine when this path is taken?

**Comment by jesperlehtinen** [comment]
I've created #12 which removes this error logging. @kilkelly please have a look and merge if you agree with this sentiment. Thanks 🙂

**Comment by kilkelly** [comment]
Hi @jesperlehtinen , thanks for your message. The error is there to inform the developer if they provide an invalid load state to the `load` method. However I completely agree that on first load this doesn't make sense as it won't exist anyhow. Rather than remove this warning / error I would propose one of two options to tackle this:

1. Add a boolean `disableInvalidLoadWarning` property to the `load` method's object argument. This would give a developer the option to disable this warning / error if they want to. Example:
```sh
load({ 
  states: ["user", "products"],
  namespace: "my_cool_app",
  disableInvalidLoadWarning: true
})
```
`disableInvalidLoadWarning`'s default would be `false`

2. Rather than use `console.error` to display the message we could change it to the less harsh `console.warn` or `console.info`. This may not trigger some CI tests as @danielwaltz mentioned above and makes more sense as an invalid load is not an error in a strict sense i,e, application will not crash as a result.

Let me know what you guys think.

**Comment by danielwaltz** [comment]
@kilkelly @jesperlehtinen I think either would be a valid solution. Honestly having both implemented would be the most ideal situation in my opinion - maybe change it to use `console.warning` instead and have an option to suppress all warnings as a config like `disableWarnings: true` with `false` being the default.

**Comment by jesperlehtinen** [comment]
@kilkelly thanks for the quick feedback. I agree with @danielwaltz, the config solution (with `console.warn` instead of `error`) seems pragmatic and sufficient, and does not break existing functionality.

**Comment by jesperlehtinen** [comment]
@kilkelly I've created a new PR #13 for a config flag to disable warnings, and changed `console.error` to `warn` for missing namespaces.

**Comment by jesperlehtinen** [comment]
@kilkelly Awesome 😄I'll go ahead and close my PR. Thanks for the quick work!

**Comment by kilkelly** [comment]
Thanks @jesperlehtinen 👍

**Comment by jesperlehtinen** [comment]
@kilkelly I've upgraded the version for our project and it seems to work just fine. Thanks again!

**Comment by kilkelly** [comment]
That's what I like to hear 👍

**Comment by danielwaltz** [comment]
Perfect! Thanks guys! Closing the issue.
