### ISSUE TITLE
adding tests?

### ISSUE THREAD

**Issue by Jbarget** [kilkelly/redux-localstorage-simple#2]
Hey Frank,

Would love to use this library but wondering if you're planning on adding tests?
cheers

**Comment by kilkelly** [comment]
Hi Jbarget, yes I plan to include tests in the next minor release.
Kind regards.

**Comment by kilkelly** [comment]
I'll try to get them added within the week.

**Comment by kilkelly** [comment]
Hi Jbarget, I've just released v1.2.0 which includes tests. Because the package uses LocalStorage I decided to run tests through the browser, rather than mock LocalStorage to allow testing in Mocha, Tape etc...

When your clone the repo you will find a file **test/test.html** which once you open it in a browser will run the tests.

Please let me know if they run correctly for you.
